name:                ioopm-lang
version:             0.1.0.0
github:              "maxxen/ioopm-lang"
license:             MIT
author:              "Max Gabrielsson"
maintainer:          "max@gabrielsson.com"
copyright:           "2019 Max Gabrielsson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            ioopm language, but in haskell
# category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Maxxen/ioopm-lang#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - mtl
  - transformers
  - containers
  - unordered-containers

executables:
  ioopm-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ioopm-lang

tests:
  ioopm-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ioopm-lang
